# Generated by Django 3.1.4 on 2021-02-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Match',
        ),
    ]
